### ISSUE TITLE
Build LocalIC binaries for outside workflow actions

### ISSUE THREAD

**Issue by Reecepbcups** [strangelove-ventures/interchaintest#791]
depends on #410 for a release/tag cycle.

Without this, a fresh build is required every time for CI in outside repos. It would be nice to just pull from here & build every time as we expand

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout interchaintest
        uses: actions/checkout@v4
        with:
            repository: strangelove-ventures/interchaintest
            path: interchaintest
            ref: 'reece/rust'

      - name: Setup go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v4
        with:
            go-version: ${{ env.GO_VERSION }}

      - name: build local-interchain        
        run: cd interchaintest/local-interchain && go mod tidy && make install

      - name: Upload localic artifact
        uses: actions/upload-artifact@v3
        with:
          name: local-ic
          path: ~/go/bin/local-ic  
```

Instead we could just download from the latest via a wget of the bin, and allow an override to specify a tag/version (ex: IBC 8 is v8.0.0/local-ic)
